Repository solo-io/gloo, pull requests merged in 2024-11, with the labels that each got.

#10351 Bump kubectl to match the k8s deps in go.mod
  changelog/v1.18.0-beta35/bump-kubectl-image.yaml
  jobs/kubectl/Dockerfile
  jobs/kubectl/Dockerfile.distroless
Labels: keep pr updated

#10355 Deprecate GraphQL
  changelog/v1.18.0-beta35/deprecate-graphql.yaml
  docs/content/guides/graphql/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/graphql/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.go
  projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto
  projects/gloo/api/v1/options/graphql/graphql.proto
  projects/gloo/api/v1/options/service_spec.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.go
  projects/gloo/pkg/api/v1/options/graphql/graphql.pb.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/settings.pb.go
Labels: keep pr updated

#10359 Remove hardcoded namespace in tracing test v1.17.x
  changelog/v1.17.17/remove-hardcoded-namespace-in-tracing-test-v1.17.x.yaml
  test/kube2e/upgrade/upgrade_utils_test.go
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/tracing/testdata/gateway.yaml
  test/kubernetes/e2e/features/tracing/testdata/tracing.yaml
  test/kubernetes/e2e/features/tracing/types.go
  test/kubernetes/testutils/helper/util_test.go
Labels: keep pr updated

#10352 Portal Auth API
  changelog/v1.18.0-beta35/portal-auth-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.uniquehash.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.uniquehash.go
Labels: keep pr updated, work in progress

#10363 Up-port fix for hardcoded namespace in tracing test
  changelog/v1.18.0-beta35/remove-hardcoded-namespace-in-tracing-test-master.yaml
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/tracing/testdata/gateway.yaml
  test/kubernetes/e2e/features/tracing/testdata/tracing.yaml
  test/kubernetes/e2e/features/tracing/types.go
Labels: bug

#5006 Add categories to GG CRDs
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta35/GG-CRD-categories.yaml
  devel/testing/kube-e2e-tests.md
  install/helm/gloo/.helmignore
  install/helm/gloo/crds/README.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_ListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml
  install/helm/gloo/crds/ratelimit_config.yaml
  test/kube2e/README.md
  test/kubernetes/e2e/features/crd_categories/suite.go
  test/kubernetes/e2e/features/crd_categories/testdata/manifests/empty-virtualservice.yaml
  test/kubernetes/e2e/features/crd_categories/types.go
  test/kubernetes/e2e/features/helm/suite.go
  test/kubernetes/e2e/features/helm/types.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
Labels: keep pr updated

#10229 gateway2: Add readiness and liveness probes to the kube gloo gateway pod
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta35/add-readiness-liveness-probe.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway2/api/v1alpha1/gateway_parameters.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/test/k8sgateway_test.go
  pkg/utils/cmdutils/cmd.go
  pkg/utils/cmdutils/local.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  test/kubernetes/e2e/features/zero_downtime_rollout/suite.go
  test/kubernetes/e2e/features/zero_downtime_rollout/testdata/route-with-service.yaml
  test/kubernetes/e2e/features/zero_downtime_rollout/testdata/service-for-route.yaml
  test/kubernetes/e2e/features/zero_downtime_rollout/types.go
  test/kubernetes/e2e/tests/base/base_suite.go
  test/kubernetes/e2e/tests/manifests/zero-downtime-rollout.yaml
  test/kubernetes/e2e/tests/zero_downtime_test.go
  test/kubernetes/e2e/tests/zero_downtime_tests.go
Labels: keep pr updated, work in progress

#10378 rc1 changelogs
  changelog/v1.18.0-rc1/GG-CRD-categories.yaml
  changelog/v1.18.0-rc1/add-readiness-liveness-probe.yaml
  changelog/v1.18.0-rc1/bump-kubectl-image.yaml
  changelog/v1.18.0-rc1/crdcheck.yaml
  changelog/v1.18.0-rc1/deprecate-graphql.yaml
  changelog/v1.18.0-rc1/helm-doc-gen.yaml
  changelog/v1.18.0-rc1/move-changelogs.yaml
  changelog/v1.18.0-rc1/portal-auth-api.yaml
  changelog/v1.18.0-rc1/remove-external-apis.yaml
  changelog/v1.18.0-rc1/remove-hardcoded-namespace-in-tracing-test-master.yaml
Labels: keep pr updated, work in progress

#10375 v1.16.x - Fix "should return latest patch" test
  changelog/v1.16.23/upgrade-patch-test-fix.yaml
  test/kube2e/upgrade/upgrade_utils_test.go
Labels: keep pr updated

#10376 v1.15.x - Fix "should return latest patch" test
  changelog/v1.15.35/fix-latest-patch-test.yaml
  test/kube2e/upgrade/upgrade_utils_test.go
Labels: keep pr updated

#10381 Bump timeout on e2e tests
  .github/workflows/nightly-tests.yaml
  changelog/v1.18.0-rc2/e2e-timeout-bump.yaml
Labels: keep pr updated, work in progress

#10386 Set k8sgateway api version when setting up e2e test cluster
  .github/workflows/.env/nightly-tests/max_versions.env
  .github/workflows/.env/nightly-tests/min_versions.env
  .github/workflows/composite-actions/setup-kind-cluster/action.yaml
  .github/workflows/nightly-tests.yaml
  changelog/v1.18.0-rc2/conformance-version-in-env.yaml
Labels: keep pr updated

#10391 bugfix: fix eds updates when discovery enabled
  changelog/v1.18.0-rc2/eds-discovery.yaml
  projects/gateway2/krtcollections/endpoints.go
  projects/gateway2/krtcollections/endpoints_test.go
  projects/gateway2/krtcollections/uniqueclients.go
  projects/gateway2/krtcollections/uniqueclients_test.go
  projects/gateway2/setup/ggv2setup.go
  projects/gateway2/setup/ggv2setup_test.go
  projects/gateway2/utils/hash.go
Labels: keep pr updated, work in progress

#10393 .trivyignore: ignore cve
  .trivyignore
  changelog/v1.18.0-rc2/trivy-ignore.yaml
Labels: keep pr updated

#10388 Remove symlink to crd file in kubernetes e2e test data
  changelog/v1.18.0-rc2/remove-manifest-symlink.yaml
  projects/gateway2/crds/crds.go
  test/kubernetes/e2e/features/services/httproute/testdata/tcproute-crd.yaml
  test/kubernetes/e2e/features/services/httproute/types.go
Labels: keep pr updated

#10389 Fix/docsrelease
  changelog/v1.18.0-rc2/docsgen.yaml
  docs/Makefile
  docs/cmd/generate_docs.go
  go.mod
  go.sum
Labels: keep pr updated, work in progress

#10387 Adds Support for TCPRoute Status
  changelog/v1.18.0-rc2/issue_10365.yaml
  projects/gateway2/proxy_syncer/proxy_syncer_test.go
  projects/gateway2/query/mocks/mock_queries.go
  projects/gateway2/query/query_test.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/listener/gateway_listener_translator_test.go
  projects/gateway2/translator/plugins/mirror/mirror_plugin_test.go
  projects/gateway2/translator/testutils/inputs/tcp-routing/invalid-backend.yaml
  projects/gateway2/translator/testutils/inputs/tcp-routing/missing-backend.yaml
  projects/gateway2/translator/testutils/outputs/tcp-routing/invalid-backend.yaml
  projects/gateway2/translator/testutils/outputs/tcp-routing/missing-backend.yaml
Labels: keep pr updated, work in progress

#10394 Don't export ValidationSplitWebhook test
  changelog/v1.18.0-rc2/dont-export-split-validation-test.yaml
  test/kubernetes/e2e/tests/validation_strict_test.go
  test/kubernetes/e2e/tests/validation_strict_tests.go
Labels: keep pr updated

#10398 CI: Adds Ginkgo Resource Condition Assertions
  changelog/v1.18.0-rc2/issue_10397.yaml
  test/kubernetes/e2e/features/services/tcproute/suite.go
  test/kubernetes/e2e/features/services/tcproute/types.go
  test/kubernetes/testutils/assertions/status.go
  test/kubernetes/testutils/cluster/kind.go
Labels: keep pr updated

#10404 feat: allow disabling pod locality in xDS
  changelog/v1.18.0-rc3/pod-xds-disable.yaml
  projects/gateway2/krtcollections/uniqueclients.go
  projects/gateway2/krtcollections/uniqueclients_test.go
  projects/gateway2/setup/ggv2setup.go
Labels: keep pr updated, work in progress

#10407 .github/workflows: do not add work in progress label by default
  .github/workflows/add-pr-label.yaml
  changelog/v1.18.0-rc3/work-in-progress-default-false.yaml
Labels: keep pr updated

#10395 test fix: allow test scenarios run more than one time
  projects/gateway2/setup/ggv2setup_test.go
Labels: keep pr updated

#10408 Fix/docs prints
  changelog/v1.18.0-rc3/docs-cleanchangelog.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10406 test/ginkgo: ensure admin server port is not selected dynamically
  changelog/v1.18.0-rc3/safe-ports-e2e.yaml
  test/ginkgo/parallel/ports.go
Labels: keep pr updated

#10409 e2e/features/tracing: reduce flakiness of entire suite, capture technical debt
  changelog/v1.18.0-rc3/span-name-flake.yaml
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/tracing/testdata/gateway.yaml
  test/kubernetes/e2e/features/tracing/testdata/gw-proxy-tracing-service.yaml
  test/kubernetes/e2e/features/tracing/types.go
Labels: keep pr updated

#10411 bugfix: propagate eds changes when annotations change.
  changelog/v1.18.0-rc3/fix-eds-update-on-add-labels.yaml
  projects/gateway2/krtcollections/endpoints.go
  projects/gateway2/krtcollections/endpoints_test.go
  projects/gateway2/proxy_syncer/cla.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/setup/ggv2setup_test.go
  projects/gloo/pkg/translator/translator.go
Labels: keep pr updated

#10400 Collect Gloo metrics and some snapshots on test failure
  changelog/v1.18.0-rc3/collect-more-artifacts-on-ci-failure.yaml
  pkg/utils/glooadminutils/admincli/client.go
  pkg/utils/kubeutils/kubectl/cli.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  test/helpers/kube_dump.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/manifests/common-recommendations.yaml
Labels: keep pr updated
