Repository solo-io/gloo, pull requests merged in 2024-12, with the labels that each got.

#10418 Refactors TCPRoute e2e tests
  changelog/v1.18.0-rc3/issue_10414.yaml
  test/kubernetes/e2e/features/services/tcproute/suite.go
  test/kubernetes/e2e/features/services/tcproute/testdata/multi-backend-service.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/multi-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/multi-ns.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/multi-tcproute.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/single-backend-service.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/single-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/single-ns.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/single-tcproute.yaml
  test/kubernetes/e2e/features/services/tcproute/types.go
  test/kubernetes/testutils/assertions/objects.go
Labels: keep pr updated

#10410 attempt to deflake ggv2 setup test
  changelog/v1.18.0-rc3/defalke-test.yaml
  projects/gateway2/proxy_syncer/perclient.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/proxy_syncer/xdswrapper.go
  projects/gateway2/proxy_syncer/xdswrapper_test.go
  projects/gateway2/setup/ggv2setup_test.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/edge-cases/no_route.yaml
  projects/gateway2/translator/testutils/outputs/no_route.yaml
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#10423 gateway2/delegation: add unit test for multi-level multi-parent config
  changelog/v1.17.17/1.17-deleg.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/delegation/bug-10379.yaml
  projects/gateway2/translator/testutils/outputs/delegation/bug-10379.yaml
Labels: keep pr updated

#10417 Feat/large validation
  Makefile
  changelog/v1.18.0-rc3/validate-large-configs.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/envoyinit/pkg/runner/run.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/README.md
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kubernetes/e2e/features/validation/full_envoy_validation/suite.go
  test/kubernetes/e2e/features/validation/testdata/valid-resources/large-configuration.yaml
  test/kubernetes/e2e/features/validation/types.go
  test/kubernetes/e2e/features/validation/validation_reject_invalid/suite.go
  test/kubernetes/e2e/tests/manifests/full-envoy-validation-helm.yaml
Labels: keep pr updated

#10426 skip explicitly
  test/kubernetes/e2e/features/validation/full_envoy_validation/suite.go
Labels: keep pr updated

#10429 .github: add v1.18.x to the nightly tests
  .github/workflows/docs-gen.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.19.0-beta1/1-19-main-branch-cleanup.yaml
  docs/Makefile
Labels: keep pr updated

#10428 [1.18] .github: cleanup nightly-tests, add placeholder changelog
  .github/workflows/docs-gen.yaml
  .github/workflows/nightly-tests.yaml
  changelog/v1.18.0-rc4/1-18-branch-cleanup.yaml
Labels: keep pr updated

#10435 Bump moby OSS 1.18
  changelog/v1.19.0-beta1/bump-moby.yaml
  docs/content/reference/security-updates/open_source/_index.md
  docs/layouts/shortcodes/readfile.html
  go.mod
  go.sum
Labels: keep pr updated

#10422 Docs - Deprecate aerospike
  .github/workflows/push-docs.yaml
  changelog/v1.19.0-beta1/docs-deprecation.yaml
  docs/content/guides/security/rate_limiting/enterprise/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#10421 multiarch updates
  Makefile
  changelog/v1.19.0-beta1/ci-multiarch-updates.yaml
  ci/cloudbuild/publish-artifacts.yaml
  jobs/certgen/cmd/Dockerfile
  jobs/certgen/cmd/Dockerfile.distroless
  projects/distroless/Dockerfile
  test/kube2e/containers/testrunner/Dockerfile
  test/kube2e/helper/http_echo.go
  test/kube2e/helper/testserver.go
  test/kube2e/util.go
  test/kubernetes/testutils/helper/util.go
Labels: enhancement, keep pr updated

#10439 Make cluster stats names more parseable
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.19.0-beta1/cluster-stats-names.yaml
  pkg/utils/envoyutils/admincli/README.md
  pkg/utils/envoyutils/admincli/client.go
  pkg/utils/envoyutils/admincli/client_test.go
  projects/discovery/pkg/fds/updater.go
  projects/gateway2/proxy_syncer/cla.go
  projects/gateway2/proxy_syncer/destrule.go
  projects/gateway2/proxy_syncer/upstreams.go
  projects/gateway2/setup/ggv2setup.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/azure/plugin.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert.go
  projects/gloo/pkg/plugins/rest/plugin.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/translator/utils_test.go
  projects/gloo/pkg/upstreams/conversions.go
  projects/gloo/pkg/upstreams/kubernetes/conversions.go
  projects/gloo/pkg/upstreams/kubernetes/conversions_test.go
  projects/gloo/pkg/upstreams/kubernetes/upstream_client.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
  test/e2e/happypath_test.go
  test/helpers/kube_dump.go
  test/kubernetes/e2e/features/metrics/suite.go
  test/kubernetes/e2e/features/metrics/testdata/gateway-and-route-to-service.yaml
  test/kubernetes/e2e/features/metrics/testdata/gateway-and-route-to-upstream.yaml
  test/kubernetes/e2e/features/metrics/testdata/service.yaml
  test/kubernetes/e2e/features/metrics/types.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
  test/services/envoy/instance.go
Labels: keep pr updated

#10437 Bump moby 1.18
  changelog/v1.18.0-rc4/bump-moby.yaml
  docs/content/reference/security-updates/open_source/_index.md
  go.mod
  go.sum
Labels: keep pr updated

#10444 Cluster stats name [1.18]
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-rc4/cluster-stats-names.yaml
  pkg/utils/envoyutils/admincli/README.md
  pkg/utils/envoyutils/admincli/client.go
  pkg/utils/envoyutils/admincli/client_test.go
  projects/discovery/pkg/fds/updater.go
  projects/gateway2/proxy_syncer/cla.go
  projects/gateway2/proxy_syncer/destrule.go
  projects/gateway2/proxy_syncer/upstreams.go
  projects/gateway2/setup/ggv2setup.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/azure/plugin.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert.go
  projects/gloo/pkg/plugins/rest/plugin.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/translator/utils_test.go
  projects/gloo/pkg/upstreams/conversions.go
  projects/gloo/pkg/upstreams/kubernetes/conversions.go
  projects/gloo/pkg/upstreams/kubernetes/conversions_test.go
  projects/gloo/pkg/upstreams/kubernetes/upstream_client.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
  test/e2e/happypath_test.go
  test/helpers/kube_dump.go
  test/kubernetes/e2e/features/metrics/suite.go
  test/kubernetes/e2e/features/metrics/testdata/gateway-and-route-to-service.yaml
  test/kubernetes/e2e/features/metrics/testdata/gateway-and-route-to-upstream.yaml
  test/kubernetes/e2e/features/metrics/testdata/service.yaml
  test/kubernetes/e2e/features/metrics/types.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
  test/services/envoy/instance.go
Labels: keep pr updated

#10443 Doc fixes 1.17
  .github/workflows/push-docs.yaml
  changelog/v1.17.17/docs-deprecation.yaml
  docs/content/guides/security/rate_limiting/enterprise/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#10442 Doc fixes 1.18
  .github/workflows/push-docs.yaml
  changelog/v1.18.0-rc4/docs-deprecation.yaml
  docs/content/guides/security/rate_limiting/enterprise/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#10449 [1.18] multiarch updates
  Makefile
  changelog/v1.18.0-rc4/ci-multiarch-updates.yaml
  ci/cloudbuild/publish-artifacts.yaml
  jobs/certgen/cmd/Dockerfile
  jobs/certgen/cmd/Dockerfile.distroless
  projects/distroless/Dockerfile
  test/kube2e/containers/testrunner/Dockerfile
  test/kube2e/helper/http_echo.go
  test/kube2e/helper/testserver.go
  test/kube2e/util.go
  test/kubernetes/testutils/helper/util.go
Labels: keep pr updated

#10454 [1.18] fix broken GA CI build (#10453)
  Makefile
  changelog/v1.18.0-rc4/ci-multiarch-fixes.yaml
  ci/cloudbuild/publish-artifacts.yaml
Labels: keep pr updated

#10447 Doc: watchNamespaceSelectors
  changelog/v1.19.0-beta2/docs-watchns-labels.yaml
  docs/content/installation/advanced_configuration/multiple-gloo-installs.md
Labels: keep pr updated

#10457 Bumps Gateway API Dependencies
  .github/workflows/.env/nightly-tests/max_versions.env
  changelog/v1.19.0-beta2/issue_10456.yaml
  ci/kind/setup-kind.sh
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  projects/gateway2/crds/gateway-crds.yaml
  projects/gateway2/crds/tcproute-crd.yaml
Labels: keep pr updated

#10450 Additional CLI debug commands
  .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
  changelog/v1.19.0-beta2/CLI-debug-additions.yaml
  devel/debugging/glooctl-debug.md
  docs/content/reference/cli/glooctl.md
  docs/content/reference/cli/glooctl_debug.md
  docs/content/reference/cli/glooctl_debug_logs.md
  docs/content/reference/cli/glooctl_debug_yaml.md
  docs/content/reference/cli/glooctl_proxy.md
  docs/content/reference/cli/glooctl_proxy_address.md
  docs/content/reference/cli/glooctl_proxy_dump.md
  docs/content/reference/cli/glooctl_proxy_logs.md
  docs/content/reference/cli/glooctl_proxy_served-config.md
  docs/content/reference/cli/glooctl_proxy_snapshot.md
  docs/content/reference/cli/glooctl_proxy_stats.md
  docs/content/reference/cli/glooctl_proxy_url.md
  pkg/cliutil/input_test.go
  pkg/cliutil/testutil/testutil.go
  pkg/utils/envoyutils/admincli/client.go
  pkg/utils/kubeutils/kubectl/cli.go
  pkg/utils/kubeutils/portforward/cli_portforwarder.go
  pkg/utils/statedumputils/state_dump.go
  projects/gloo/cli/pkg/cmd/add/route_interactive_test.go
  projects/gloo/cli/pkg/cmd/create/authconfig/authconfig_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_interactive_test.go
  projects/gloo/cli/pkg/cmd/create/upstream_interactive_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_glooe_test.go
  projects/gloo/cli/pkg/cmd/debug/root.go
  projects/gloo/cli/pkg/cmd/debug/root_test.go
  projects/gloo/cli/pkg/cmd/edit/route/extauth_test.go
  projects/gloo/cli/pkg/cmd/edit/settings/extauth_test.go
  projects/gloo/cli/pkg/cmd/edit/settings/ratelimit/ratelimit_test.go
  projects/gloo/cli/pkg/cmd/edit/upstream/root_test.go
  projects/gloo/cli/pkg/cmd/edit/virtualservice/root_test.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  projects/gloo/cli/pkg/cmd/gateway/root.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/constants/commands.go
  projects/gloo/cli/pkg/flagutils/debug.go
  projects/gloo/cli/pkg/surveyutils/route_test.go
  projects/gloo/pkg/servers/admin/server.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kubernetes/e2e/features/helm/suite.go
  test/kubernetes/e2e/test.go
Labels: keep pr updated

#10465 Gloo Gateway 1.18.0
  changelog/v1.18.0/prep-ga-changelog.yaml
Labels: keep pr updated

#10466 PERSIST_INSTALL flag for e2e tests
  changelog/v1.19.0-beta3/k8s-e2e-skip-install-update.yaml
  pkg/utils/envutils/env.go
  test/helpers/glooctl_debug_dump.go
  test/kube2e/README.md
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/helper/install.go
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/assertions/glooctl.go
  test/testutils/env.go
Labels: keep pr updated

#10458 Add support for listener level warnings
  changelog/v1.19.0-beta3/allow-listener-warnings.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  projects/gateway/pkg/reporting/add_proxy_validation_result.go
  projects/gateway/pkg/reporting/add_proxy_validation_result_test.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/cli/pkg/cmd/debug/root_test.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.clone.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.uniquehash.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/network_filters.go
  projects/gloo/pkg/translator/reporting.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  projects/gloo/pkg/utils/validation/proxy_validation_test.go
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/gateway-no-upstream.yaml
  test/kubernetes/e2e/features/validation/testdata/otel-upstream.yaml
  test/kubernetes/e2e/features/validation/testdata/setup-otel.yaml
  test/kubernetes/e2e/features/validation/types.go
  test/kubernetes/e2e/features/validation/validation_allow_warnings/suite.go
Labels: keep pr updated

#10479 PERSIST_INSTALL option followup
  changelog/v1.19.0-beta3/k8s-e2e-skip-install-update-followup.yaml
  pkg/utils/envutils/env.go
  test/kube2e/helper/install.go
  test/kubernetes/testutils/assertions/glooctl.go
  test/testutils/env.go
  test/testutils/install.go
Labels: keep pr updated

#10475 Docs for 1.18
  changelog/v1.19.0-beta3/docs-prepare-1.18.yaml
  docs/active_versions.json
  docs/content/operations/upgrading/faq.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#10473 Docs workflow 1.17
  .github/workflows/push-docs.yaml
  changelog/v1.17.17/docs-workflow.yaml
Labels: keep pr updated

#10486 Docs sec update
  changelog/v1.19.0-beta3/docs-sec-update.yaml
  docs/content/reference/security-updates/enterprise/_index.md
Labels: keep pr updated

#10470 gateway2/delegation: enable inherited policy overrides
  changelog/v1.19.0-beta3/fix-sp-7315.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/routeutils/utils.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance_child_override_allow.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_allow.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_allow.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_allow.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10491 [1.18] tests: Fix failing K8sGateway/Metrics test in enterprise
  changelog/v1.18.1/fix-metrics-suite.yaml
  test/kubernetes/e2e/features/helm/suite.go
  test/kubernetes/e2e/features/metrics/suite.go
  test/kubernetes/e2e/features/upgrade/suite.go
  test/kubernetes/e2e/features/watch_namespace_selector/suite.go
  test/kubernetes/e2e/features/zero_downtime_rollout/suite.go
  test/kubernetes/e2e/tests/base/base_suite.go
Labels: keep pr updated

#10493 add note about backports
  changelog/v1.19.0-beta3/backport-changelog-note.yaml
  devel/contributing/backports.md
Labels: keep pr updated

#10480 tests: Fix flakey TestConfigureNotAttachedHttpListenerOptions
  changelog/v1.19.0-beta3/fix-flakey-TestConfigureNotAttachedHttpListenerOptions.yaml
  test/gomega/matchers/pod.go
  test/kubernetes/e2e/features/http_listener_options/http_lis_opt_suite.go
  test/kubernetes/testutils/assertions/pods.go
Labels: keep pr updated

#10494 ai semantic caching distance threshold API update
  changelog/v1.19.0-beta3/ai-semantic-caching-distance.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
Labels: keep pr updated

#10496 [backport] gateway2/delegation: enable inherited policy overrides (#10470)
  changelog/v1.17.17/fix-sp-7315.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/routeutils/utils.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance_child_override_allow.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_allow.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_allow.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_allow.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10469 Improving onboarding
  changelog/v1.19.0-beta3/improved-onboarding-docs.yaml
  devel/testing/e2e-tests.md
  devel/testing/kube-e2e-tests.md
  devel/testing/unit-tests.md
  docs/content/guides/dev/_index.md
  docs/content/guides/dev/building-and-deploying-gloo.md
  docs/content/guides/dev/setting-up-dev-environment.md
  docs/content/introduction/development.md
Labels: keep pr updated

#10489 [1.18] Add support for listener level warnings
  changelog/v1.18.1/allow-listener-warnings.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  projects/gateway/pkg/reporting/add_proxy_validation_result.go
  projects/gateway/pkg/reporting/add_proxy_validation_result_test.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.clone.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.uniquehash.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/network_filters.go
  projects/gloo/pkg/translator/reporting.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  projects/gloo/pkg/utils/validation/proxy_validation_test.go
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/gateway-no-upstream.yaml
  test/kubernetes/e2e/features/validation/testdata/otel-upstream.yaml
  test/kubernetes/e2e/features/validation/testdata/setup-otel.yaml
  test/kubernetes/e2e/features/validation/types.go
  test/kubernetes/e2e/features/validation/validation_allow_warnings/suite.go
Labels: keep pr updated

#10497 [backport] gateway2/delegation: enable inherited policy overrides (#10470)
  changelog/v1.18.1/fix-sp-7315.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/routeutils/utils.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance_child_override_allow.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_allow.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_allow.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_allow.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10504 [1.15] ci: bump EOL github upload action
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/nightly-tests.yaml
  changelog/v1.15.35/bump-upload-artifact-115.yaml
Labels: keep pr updated

#10505 [1.18] tests: Fix flakey TestConfigureNotAttachedHttpListenerOptions
  changelog/v1.18.1/fix-flakey-TestConfigureNotAttachedHttpListenerOptions.yaml
  test/gomega/matchers/pod.go
  test/kubernetes/e2e/features/http_listener_options/http_lis_opt_suite.go
  test/kubernetes/testutils/assertions/pods.go
Labels: keep pr updated

#10506 Crypto 1.31 bump v1.19.x
  changelog/v1.19.0-beta3/crypto-bump.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#10509 Crypto 1.31 bump v1.16.x
  changelog/v1.16.23/crypto-bump.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#10507 Crypto 1.31 bump v1.18.x
  changelog/v1.18.1/crypto-bump.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#10514 Update x/net to v0.33.0
  changelog/v1.17.18/xnet-bump.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10517 Update x/net to v0.33.0
  changelog/v1.19.0-beta3/xnet-bump.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10516 Update x/net to v0.33.0
  changelog/v1.18.1/xnet-bump.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10515 Update x/net to v0.33.0
  changelog/v1.16.23/bump-xnet.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10520 gateway2: reconcile on HTTPRoute annotation change
  changelog/v1.19.0-beta3/httproute-annotation.yaml
  projects/gateway2/controller/controller.go
Labels: keep pr updated

#10522 gateway2: reconcile on HTTPRoute annotation change
  changelog/v1.18.2/httproute-annotation.yaml
  projects/gateway2/controller/controller.go
Labels: keep pr updated

#10521 [backport] gateway2: reconcile on HTTPRoute annotation change
  changelog/v1.17.19/httproute-annotation.yaml
  projects/gateway2/controller/controller.go
Labels: keep pr updated

#10518 make: Bump envoy for recent cve release
  Makefile
  changelog/v1.19.0-beta3/envoy-cve.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
  install/test/fixtures/envoy_config/overload_manager.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  install/test/fixtures/envoy_config/tcp_keepalive.yaml
  install/test/helm_test.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  test/services/envoy/bootstrap_builder.go
Labels: keep pr updated

#10523 [1.17] Span name flake
  changelog/v1.17.19/span-name-flake.yaml
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/tracing/testdata/gateway.yaml
  test/kubernetes/e2e/features/tracing/testdata/gw-proxy-tracing-service.yaml
  test/kubernetes/e2e/features/tracing/types.go
Labels: keep pr updated

#10511 Move `glooctl debug` unit tests to e2e tests
  changelog/v1.19.0-beta3/fix-glooctl-debug-tests.yaml
  projects/gloo/cli/pkg/cmd/debug/root_test.go
  projects/gloo/cli/pkg/testutils/cli.go
  test/kubernetes/e2e/features/glooctl/debug_suite.go
Labels: keep pr updated

#10526 Doc fixes [1.19]
  .github/workflows/push-docs.yaml
  changelog/v1.19.0-beta3/docs-fixes.yaml
  docs/content/guides/graphql/observability.md
  docs/content/introduction/faq.md
  docs/content/operations/debugging_gloo/_index.md
Labels: keep pr updated

#10531 Docs: workflow adjustment, version bumps
  .github/workflows/push-docs.yaml
  changelog/v1.19.0-beta3/docs-fixes-2.yaml
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_latest_minor.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/static/content/version_geoss_n-1_minor.md
  docs/content/static/content/version_geoss_n-2_minor.md
Labels: keep pr updated

#10532 [1.18 backport] Docs: workflow adjustment, version bumps
  .github/workflows/push-docs.yaml
  changelog/v1.18.3/docs-fixes.yaml
  docs/content/guides/graphql/observability.md
  docs/content/introduction/faq.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#10533 [1.17 backport] Docs: workflow adjustment, version bumps
  .github/workflows/push-docs.yaml
  changelog/v1.17.20/docs-fixes.yaml
  docs/content/guides/graphql/observability.md
  docs/content/introduction/faq.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#10438 Moby CVEs trivyignore
  .trivyignore
  changelog/v1.19.0-beta3/moby-cves-trivyignore.yaml
Labels: keep pr updated

#10512 [1.16] ci: Add run attempt to artifact name
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  changelog/v1.16.24/run-attempt-116.yaml
Labels: keep pr updated

#10513 [1.15] ci: Add run attempt to artifact name
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  changelog/v1.15.36/run-attempt-115.yaml
Labels: keep pr updated

#10537 trivy: ignore CVE-2024-45338
  .trivyignore
  changelog/v1.19.0-beta3/kubectl-cve.yaml
Labels: keep pr updated

#10536 Fix regex field in ai.proto
  .github/workflows/push-docs.yaml
  changelog/v1.19.0-beta3/docs-ai-regex-fix.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
Labels: keep pr updated, work in progress

#10487 Doc sec update oss
  changelog/v1.19.0-beta3/doc-sec-update-oss.yaml
  docs/content/reference/security-updates/open_source/_index.md
Labels: keep pr updated

#10535 .github/workflows: disable performance tests
  .github/workflows/nightly-tests.yaml
  changelog/v1.19.0-beta3/disable-performance-tests.yaml
  devel/testing/performance-tests.md
Labels: keep pr updated

#10420 add external traffic policy for gw2 gw params
  changelog/v1.19.0-beta3/external-traffic-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway2/api/v1alpha1/gateway_parameters.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/merge_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  test/kubernetes/e2e/features/deployer/suite.go
Labels: keep pr updated
