Repository solo-io/gloo, pull requests merged in 2025-03, with the labels that each got.

#10662 Attach jwt failure status to metadata
  changelog/v1.19.0-beta13/attach-jwt-failure-status-to-metadata.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.proto
  projects/gloo/api/v1/enterprise/options/jwt/jwt.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.uniquehash.go
Labels: keep pr updated

#10675 Docs image fix
  changelog/v1.18.11/docs-image-fix.yaml
  docs/content/img/ui-dashboard.png
  docs/content/img/ui-graph.png
Labels: keep pr updated

#10676 GRPC Passthrough documentation and test server update
  changelog/v1.19.0-beta13/passthrough-qol.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/test-no-auth-vs.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/test-no-auth-vs.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/examples/grpc-passthrough-auth/README.md
  docs/examples/grpc-passthrough-auth/go.mod
  docs/examples/grpc-passthrough-auth/go.sum
  docs/examples/grpc-passthrough-auth/pkg/auth/v3/auth.go
  docs/examples/http-passthrough-auth/README.md
  docs/examples/http-passthrough-auth/go.mod
  docs/examples/http-passthrough-auth/go.sum
  docs/examples/http-passthrough-auth/pkg/auth/v1/auth.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#10644 Upgrading v1.17.x to Go 1.23.3
  changelog/v1.17.27/go-123.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated, work in progress

#10645 Upgrade v1.16.x to Go 1.23
  changelog/v1.16.24/go-123.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
  test/kube2e/gloo/eds_test.go
  test/kube2e/gloo/happypath_test.go
Labels: keep pr updated

#10670 Forward porting Gloo service lookup by labels to 1.18.x
  changelog/v1.18.12/discover-gloo-service-with-labels.yaml
  pkg/utils/kubeutils/names.go
  projects/gloo/pkg/syncer/setup/controlplane.go
  projects/gloo/pkg/syncer/setup/controlplane_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/kubernetes/e2e/features/deployer/suite.go
Labels: keep pr updated

#10681 [main] Bump go to 1.24.1
  changelog/v1.19.0-beta13/go-bump-1.24.1.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#10683 [1.18] Bump Go to 1.23.7
  changelog/v1.18.12/go-bump-1.23.7.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#10684 [1.17] Bump Go to 1.23.7 (#10683)
  changelog/v1.17.27/go-bump-1.23.7.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#10685 [1.16] Bump Go to 1.23.7 (#10683)
  changelog/v1.16.24/go-bump-1.23.7.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#10686 [1.15] Bump Go to 1.23.7 (#10683)
  changelog/v1.15.36/go-bump-1.23.7.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#10687 feat: support http2 and h2c app protocol
  Makefile
  changelog/v1.19.0-beta13/support-approto.yaml
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_http2_annotation_converter.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
  test/gomega/matchers/have_http_response.go
  test/gomega/matchers/have_protocol.go
  test/gomega/matchers/have_protocol_test.go
  test/gomega/transforms/curl.go
  test/gomega/transforms/transforms.go
  test/kubernetes/e2e/features/services/httproute/suite.go
  test/kubernetes/e2e/features/services/httproute/testdata/http2-service-for-route.yaml
  test/kubernetes/e2e/features/services/httproute/types.go
Labels: keep pr updated

#10682 GRPC access logging of filter state
  changelog/v1.19.0-beta13/grpc-access-log-filter-states.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/als/als.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_ListenerOption.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/accesslogger/pkg/runner/run.go
  projects/gloo/api/v1/options/als/als.proto
  projects/gloo/pkg/api/v1/options/als/als.pb.clone.go
  projects/gloo/pkg/api/v1/options/als/als.pb.equal.go
  projects/gloo/pkg/api/v1/options/als/als.pb.go
  projects/gloo/pkg/api/v1/options/als/als.pb.hash.go
  projects/gloo/pkg/api/v1/options/als/als.pb.uniquehash.go
  projects/gloo/pkg/plugins/als/converter.go
  projects/gloo/pkg/plugins/als/plugin_test.go
Labels: keep pr updated

#10691 1.18.x/grpc access log filter state
  changelog/v1.18.13/grpc-access-log-filter-states.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/als/als.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_ListenerOption.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/accesslogger/pkg/runner/run.go
  projects/gloo/api/v1/options/als/als.proto
  projects/gloo/pkg/api/v1/options/als/als.pb.clone.go
  projects/gloo/pkg/api/v1/options/als/als.pb.equal.go
  projects/gloo/pkg/api/v1/options/als/als.pb.go
  projects/gloo/pkg/api/v1/options/als/als.pb.hash.go
  projects/gloo/pkg/api/v1/options/als/als.pb.uniquehash.go
  projects/gloo/pkg/plugins/als/converter.go
  projects/gloo/pkg/plugins/als/plugin_test.go
Labels: keep pr updated

#10693 Update ENVOY_BINARY documentation
  changelog/v1.19.0-beta13/update-e2e-docs.yaml
  test/e2e/README.md
  test/testutils/env.go
Labels: keep pr updated

#10694 Bump base image to alpine to 3.21.3
  Makefile
  changelog/v1.19.0-beta13/bump-alpine.yaml
  example/proxycontroller/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
Labels: keep pr updated

#10697 [1.17] Bump base image to alpine to 3.21.3
  Makefile
  changelog/v1.17.27/bump-alpine.yaml
  example/proxycontroller/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
Labels: keep pr updated

#10699 [1.15] Bump base image to alpine to 3.21.3
  Makefile
  changelog/v1.15.36/bump-alpine.yaml
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#10696 [1.18] Bump base image to alpine to 3.21.3
  Makefile
  changelog/v1.18.13/bump-alpine.yaml
  example/proxycontroller/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
Labels: keep pr updated

#10703 Fix route delegation flakes
  changelog/v1.19.0-beta14/delegation-flakes.yaml
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/testdata/common.yaml
  test/kubernetes/e2e/features/route_delegation/types.go
Labels: keep pr updated

#10695 Added test for HTTP tunneling
  changelog/v1.19.0-beta14/http-tunnel-tests.yaml
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/defaults/testdata/httpbin.yaml
  test/kubernetes/e2e/features/http_tunnel/suite.go
  test/kubernetes/e2e/features/http_tunnel/testdata/edge.yaml
  test/kubernetes/e2e/features/http_tunnel/testdata/gateway.yaml
  test/kubernetes/e2e/features/http_tunnel/testdata/proxy.yaml
  test/kubernetes/e2e/features/http_tunnel/testdata/squid.yaml
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/edge_gw_tests.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
Labels: keep pr updated

#10704 [1.18] Fix route delegation flakes
  changelog/v1.18.14/delegation-flakes.yaml
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/testdata/common.yaml
  test/kubernetes/e2e/features/route_delegation/types.go
Labels: keep pr updated

#10705 [1.17] Fix route delegation flakes
  changelog/v1.17.28/delegation-flakes.yaml
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/testdata/common.yaml
  test/kubernetes/e2e/features/route_delegation/types.go
  test/kubernetes/testutils/assertions/pods.go
Labels: keep pr updated

#10706 HTTP tunneling documentation improvements
  changelog/v1.19.0-beta14/improve-http-tunneling-docs.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  projects/gloo/api/v1/enterprise/options/jwt/jwt.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.go
Labels: keep pr updated

#10707 Doc fixes for week ending Mar 14, 2025
  changelog/v1.19.0-beta14/doc-fixes.yaml
  docs/content/guides/security/waf/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: documentation

#10701 Aws lambda 429 fix
  Makefile
  changelog/v1.19.0-beta14/aws-lambda-429-fix.yaml
Labels: keep pr updated

#10715 helm: Add the option to disable disgests
  changelog/v1.19.0-beta15/disable-digest.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#10717 [1.17] bump: envoy to 1.30.10
  Makefile
  changelog/v1.17.28/envoy-extproc-fix.yaml
Labels: keep pr updated

#10718 [1.18] Bump/envoy 1.31.6
  Makefile
  changelog/v1.18.14/envoy-bump-extproc.yaml
Labels: keep pr updated

#10721 [backport] gateway2/delegation: enable wildcard namespace for label selection
  changelog/v1.18.14/deleg-label.yaml
  projects/gateway2/query/httproute.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/delegation/label_based_wildcard_ns.yaml
  projects/gateway2/translator/testutils/outputs/delegation/label_based_wildcard_ns.yaml
  projects/gateway2/wellknown/delegation.go
Labels: keep pr updated

#10714 GW API topologySpreadConstraints
  changelog/v1.19.0-beta15/add-topologyspreadconstraints.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway2/api/v1alpha1/gateway_parameters.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
Labels: keep pr updated

#10725 gateway2/delegation: use a wildcard namespace
  changelog/v1.19.0-beta16/deleg-wildcard.yaml
  projects/gateway2/query/httproute.go
  projects/gateway2/query/httproute_test.go
  projects/gateway2/query/query.go
  projects/gateway2/translator/testutils/inputs/delegation/label_based_wildcard_ns.yaml
  projects/gateway2/wellknown/delegation.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/testdata/label_selector.yaml
  test/kubernetes/e2e/features/route_delegation/types.go
Labels: keep pr updated

#10724 [WIP] Implementing a plugin interface for tunneling that is krt-safe
  changelog/v1.19.0-beta16/plugin-interface-for-tunneling-gateway2.yaml
  projects/gateway2/proxy_syncer/perclient.go
  projects/gateway2/proxy_syncer/upstreams.go
  projects/gloo/pkg/plugins/plugins.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/tunneling/plugin.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
Labels: keep pr updated

#10727 Pin FirebaseExtended/action-hosting-deploy version
  .github/workflows/docs-gen.yaml
  changelog/v1.19.0-beta16/ci-check.yaml
Labels: keep pr updated

#10731 V1.16 firebase ci
  .github/workflows/docs-gen.yaml
  changelog/v1.16.25/ci-check.yaml
Labels: keep pr updated

#10736 Fix 1.18 e2e test ref
  .github/workflows/nightly-tests.yaml
  changelog/v1.19.0-beta16/1.18-nightly-ref-fix.yaml
Labels: keep pr updated

#10733 V1.17 firebase ci
  .github/workflows/docs-gen.yaml
  changelog/v1.17.29/ci-check.yaml
Labels: keep pr updated
