Repository solo-io/gloo, pull requests merged in 2025-02, with the labels that each got.

#10600 Adding TestInstallation.AssertionsT
  changelog/v1.19.0-beta6/tests-introducing-assertionst.yaml
  test/kubernetes/e2e/features/server_tls/k8s_suite.go
  test/kubernetes/e2e/test.go
Labels: keep pr updated

#10603 fix: gwp does not respect image variant
  changelog/v1.19.0-beta7/fix-gwp-fips-distroless.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/helm/gloo/templates/_helpers.tpl
  install/test/k8sgateway_test.go
Labels: keep pr updated

#10599 Reduce nooneway test failures
  changelog/v1.19.0-beta7/flake-improve-nooneway-failures.yaml
  test/kubernetes/e2e/features/server_tls/k8s_suite.go
Labels: keep pr updated

#10604 [1.18] fix: gwp does not respect image variant
  changelog/v1.18.7/fix-gwp-fips-distroless.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/helm/gloo/templates/_helpers.tpl
  install/test/k8sgateway_test.go
Labels: keep pr updated

#10605 [1.17] fix: gwp does not respect image variant
  changelog/v1.17.22/fix-gwp-fips-distroless.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/helm/gloo/templates/_helpers.tpl
  install/test/k8sgateway_test.go
Labels: keep pr updated

#10595 Update envoy-gloo to 1.32.3-patch2
  Makefile
  changelog/v1.19.0-beta7/envoy-1.32-bump.yaml
Labels: keep pr updated

#10614 Bumping solo-kit to v0.35.6
  changelog/v1.17.23/bump-solo-kit.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10615 Fix glooctl check test flake
  changelog/v1.19.0-beta8/fix_glooctl-check_test-flake.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/gloo_stats_test.go
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kubernetes/e2e/features/glooctl/check_suite.go
Labels: keep pr updated

#10625 linter changes
  .golangci.yaml
  changelog/v1.19.0-beta9/linter-yaml-changes.yaml
Labels: keep pr updated

#10629 V1.17.x linter fixes
  .golangci.yaml
  changelog/v1.17.24/linter-yaml-changes.yaml
Labels: keep pr updated

#10628 1.18.x linter cleanup
  .golangci.yaml
  changelog/v1.18.8/linter-yaml-changes.yaml
Labels: keep pr updated

#10626 [Backport v1.17.x] Fix glooctl check test flake
  changelog/v1.17.24/fix_glooctl-check_test-flake.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/gloo_stats_test.go
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kubernetes/e2e/features/glooctl/check_suite.go
Labels: keep pr updated

#10622 [Backport v1.18.x] Fix glooctl check and TestOneWayServerTlsFailsWithoutOneWayTls test flakes
  changelog/v1.18.8/fix_glooctl-check_test-flake.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/gloo_stats_test.go
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kubernetes/e2e/features/glooctl/check_suite.go
  test/kubernetes/e2e/features/server_tls/k8s_suite.go
Labels: keep pr updated

#10624 Doc fixes
  changelog/v1.19.0-beta10/docs-ai-gw.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/traffic_management/request_processing/upstream_health_checks/_index.md
  docs/content/operations/production_deployment/_index.md
  docs/content/reference/api/_index.md
Labels: keep pr updated

#10578 listener options merge what translator generates
  changelog/v1.19.0-beta10/merge-listener-options.yaml
  projects/gateway2/translator/plugins/listeneroptions/listener_options_plugin.go
  projects/gateway2/translator/plugins/listeneroptions/listener_options_plugin_test.go
  projects/gloo/pkg/utils/merge.go
Labels: needs-port-k8s

#10631 Bump nightly e2e test timeout
  .github/workflows/nightly-tests.yaml
  changelog/v1.19.0-beta10/bump-nightly-timeouts.yaml
Labels: keep pr updated

#10616 k8s 1.32 bump
  .github/workflows/.env/nightly-tests/max_versions.env
  .github/workflows/.env/nightly-tests/min_versions.env
  .github/workflows/.env/pr-tests/versions.env
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/conformance-tests.yaml
  changelog/v1.19.0-beta10/k8s-1.32-bump.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#10636 Update nightly slack bearer token
  .github/workflows/nightly-tests.yaml
  changelog/v1.19.0-beta11/test-result-slack-notifications.yaml
Labels: keep pr updated

#10641 remove "regex" from options/ai/ai.proto
  changelog/v1.18.9/ai-options-proto-fix.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
Labels: keep pr updated

#10642 ai proto update/fed console fix
  changelog/v1.19.0-beta11/ai-options-proto-fix.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
Labels: keep pr updated

#10620 Go 1.24, linter update, and resolve linter/vet issues
  .github/workflows/static-analysis.yaml
  .golangci.yaml
  changelog/v1.19.0-beta11/go-1.24.0.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  docs/content/guides/dev/setting-up-dev-environment.md
  go.mod
  go.sum
  install/test/helm_test.go
  pkg/cliutil/input.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gateway2/translator/plugins/directresponse/direct_response_plugin.go
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/debug/debug.go
  projects/gloo/cli/pkg/cmd/license/validate.go
  projects/gloo/cli/pkg/printers/check.go
  projects/gloo/pkg/plugins/pluginutils/cluster_extensions.go
  projects/gloo/pkg/utils/ssl.go
  test/e2e/health_checks_test.go
  test/gomega/matchers/json_contains.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/util.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#10650 Docs small updates
  changelog/v1.19.0-beta11/docs-small-fixes.yaml
  docs/content/guides/observability/ui/_index.txt
  docs/content/guides/observability/ui/setup.txt
  docs/content/guides/traffic_management/extproc/about.md
  docs/content/guides/traffic_management/extproc/header-manipulation.md
  docs/content/img/ui-dashboard.png
  docs/content/img/ui-graph.png
  docs/content/static/content/version-platform.md
  docs/layouts/shortcodes/readfile.html
Labels: keep pr updated

#10601 initial TLSRoute support
  .github/workflows/pr-kubernetes-tests.yaml
  Makefile
  changelog/v1.19.0-beta11/tls-route.yaml
  install/helm/gloo/templates/44-rbac.yaml
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/start.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/query/httproute.go
  projects/gateway2/query/indexers.go
  projects/gateway2/query/query.go
  projects/gateway2/query/query_test.go
  projects/gateway2/reports/reporter.go
  projects/gateway2/reports/reporter_test.go
  projects/gateway2/reports/status.go
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/listener/validation.go
  projects/gateway2/wellknown/gwapi.go
  projects/gloo/pkg/plugins/tcp/plugin.go
  projects/gloo/pkg/plugins/tls_inspector/plugin.go
  projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
  test/kubernetes/e2e/features/services/tlsroute/suite.go
  test/kubernetes/e2e/features/services/tlsroute/testdata/ca-cert.crt
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-backend-ns.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-backend-service.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-client-ns.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-backend-ns.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-backend-service.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-client-ns.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-tlsroute.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-referencegrant.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-tlsroute.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-backend-service.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-ns.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-tlsroute.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/single-backend-service.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/single-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/single-ns.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/single-tlsroute.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/tls-secret.yaml
  test/kubernetes/e2e/features/services/tlsroute/types.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
  test/kubernetes/testutils/assertions/status.go
Labels: keep pr updated, work in progress, needs-port-k8s

#10640 Add hostname override to AI upstream customHost setting
  changelog/v1.19.0-beta12/ai-upstream-custom-hostname.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
Labels: keep pr updated

#10655 fix ci build
  changelog/v1.19.0-beta12/ci-fix-build.yaml
  ci/cloudbuild/publish-artifacts.yaml
Labels: keep pr updated

#10639 [1.17] fix memory leak
  changelog/v1.17.25/fix-mem-lk.yaml
  projects/gateway2/status/status_syncer.go
Labels: keep pr updated

#10606 [1.18] plugins/aws: Requiretransform may be deprecated but still is in use
  changelog/v1.18.10/requesttransformordering.yaml
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated, work in progress

#10649 [1.18] AI backport of (#10494) and (#10640)
  changelog/v1.18.10/ai-semantic-caching-distance.yaml
  changelog/v1.18.10/ai-upstream-custom-hostname.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
Labels: keep pr updated, work in progress

#10656 [1.18] backport fix ci build (#10655)
  changelog/v1.18.10/ci-fix-build.yaml
  ci/cloudbuild/publish-artifacts.yaml
Labels: keep pr updated

#10659 fix e2e tests: gateway tls listeners must specify tls
  changelog/v1.19.0-beta13/tls-tests.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-listener-gateway-and-client.yaml
Labels: keep pr updated

#10661 fix: tls tests should not ignore cert
  changelog/v1.19.0-beta13/tls-tests-secure.yaml
  test/kubernetes/e2e/features/services/tlsroute/suite.go
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/tls-secret.yaml
Labels: keep pr updated

#10660 plugins/aws: Requiretransform may be deprecated but still is in use
  changelog/v1.19.0-beta13/requesttransformordering.yaml
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated

#10663 gateway2/status: preserve external conditions
  changelog/v1.19.0-beta13/dbg-status.yaml
  projects/gateway2/reports/reporter_test.go
  projects/gateway2/reports/status.go
Labels: keep pr updated, needs-port-k8s

#10666 [backport] gateway2/status: preserve external conditions
  changelog/v1.18.11/dbg-status.yaml
  projects/gateway2/reports/reporter_test.go
  projects/gateway2/reports/status.go
Labels: keep pr updated

#10665 add tls unit tests
  changelog/v1.19.0-beta13/tls-unit-test.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/tls-routing/basic.yaml
  projects/gateway2/translator/testutils/inputs/tls-routing/invalid-backend.yaml
  projects/gateway2/translator/testutils/inputs/tls-routing/missing-backend.yaml
  projects/gateway2/translator/testutils/inputs/tls-routing/multi-backend.yaml
  projects/gateway2/translator/testutils/outputs/tls-routing/basic-proxy.yaml
  projects/gateway2/translator/testutils/outputs/tls-routing/invalid-backend.yaml
  projects/gateway2/translator/testutils/outputs/tls-routing/missing-backend.yaml
  projects/gateway2/translator/testutils/outputs/tls-routing/multi-backend-proxy.yaml
Labels: keep pr updated

#10664 Discover Gloo service with labels
  changelog/v1.17.26/discover-gloo-service-with-labels.yaml
  pkg/utils/kubeutils/names.go
  projects/gloo/pkg/syncer/setup/controlplane.go
  projects/gloo/pkg/syncer/setup/controlplane_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/kubernetes/e2e/features/deployer/suite.go
Labels: keep pr updated

#10668 Gloo UI in Edge
  changelog/v1.19.0-beta13/docs-gloo-ui.yaml
  docs/content/guides/observability/ui/_index.md
  docs/content/guides/observability/ui/_index.txt
  docs/content/guides/observability/ui/explore.md
  docs/content/guides/observability/ui/setup.md
  docs/content/img/ui-clusters.png
  docs/content/img/ui-destinations.png
  docs/content/img/ui-gateways.png
  docs/content/img/ui-insights.png
  docs/content/img/ui-policies.png
  docs/content/img/ui-routes.png
Labels: keep pr updated

#10671 02/28 CI Updates: Upgrade `helm/kind-action` to avoid possible future CI failures
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/composite-actions/setup-kind-cluster/action.yaml
  changelog/v1.19.0-beta13/update-ci-kind-action-to-1.12.yaml
Labels: keep pr updated

#10672 Doc fixes
  changelog/v1.19.0-beta13/docs-fixes.yaml
  docs/content/guides/observability/ui/_index.md
  docs/content/reference/values.txt
  docs/content/static/content/version-platform.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#10673 Doc fixes 1.18
  changelog/v1.18.11/docs-gloo-ui.yaml
  docs/content/guides/observability/ui/_index.md
  docs/content/guides/observability/ui/explore.md
  docs/content/guides/observability/ui/setup.md
  docs/content/img/ui-clusters.png
  docs/content/img/ui-destinations.png
  docs/content/img/ui-gateways.png
  docs/content/img/ui-insights.png
  docs/content/img/ui-policies.png
  docs/content/img/ui-routes.png
  docs/content/static/content/version-platform.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated
