Repository solo-io/gloo, pull requests merged in 2025-01, with the labels that each got.

#10544 fix: create logger once instead of every iteration
  changelog/v1.19.0-beta3/memleak.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#10545 [1.18] log leak backport
  changelog/v1.18.3/memleak.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#10446 Adds `sync-gateway-api` Make Target for Managing the Gateway API Version
  Makefile
  changelog/v1.19.0-beta3/issue_10445.yaml
  ci/sync-gateway-api.sh
  projects/gateway2/crds/tcproute-crd.yaml
Labels: keep pr updated

#10548 gateway2: allow child policies to always set fields unset on the parent
  changelog/v1.19.0-beta3/policy-prefixrewrite.yaml
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10550 [backport] gateway2: allow child policies to always set fields unset on the parent
  changelog/v1.18.4/policy-prefixrewrite.yaml
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_partial.yaml
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10538 Static NodePorts for Gateway API service ports
  changelog/v1.19.0-beta3/7504-gwapi-static-node-ports.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway2/api/v1alpha1/gateway_parameters.md
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/templates/43-gatewayparameters.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
Labels: keep pr updated

#10555 gateway2: use safer merging to avoid assuming zero values as being unset
  changelog/v1.19.0-beta3/merge-check.yaml
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gloo/pkg/translator/ssl_configuration.go
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10558 [backport] gateway2: use safer merging to avoid assuming zero values as being unset
  changelog/v1.17.21/merge-check.yaml
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gloo/pkg/translator/ssl_configuration.go
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10559 [backport] gateway2: use safer merging to avoid assuming zero values as being unset
  changelog/v1.18.4/merge-check.yaml
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gloo/pkg/translator/ssl_configuration.go
  projects/gloo/pkg/utils/merge.go
Labels: keep pr updated

#10556 [main] Update push-docs workflow
  .github/workflows/push-docs.yaml
  changelog/v1.19.0-beta3/docs-workflow-fix.yaml
Labels: keep pr updated

#10560 Doc fixes 1.17
  .github/workflows/push-docs.yaml
  changelog/v1.17.22/docs-workflow-fix.yaml
Labels: keep pr updated

#10557 Doc fixes 1.18
  .github/workflows/push-docs.yaml
  changelog/v1.18.4/docs-ai-regex-fix.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
Labels: keep pr updated

#10552 [1.18 Backport] gateway params externaltrafficpolicy
  changelog/v1.18.4/external-traffic-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway2/api/v1alpha1/gateway_parameters.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/test/k8sgateway_test.go
  pkg/utils/kubeutils/service.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/merge_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/testutils/assertions/service.go
Labels: keep pr updated

#10553 Gateway SSL Extensions
  changelog/v1.19.0-beta3/7504-gwapi-static-node-ports.yaml
  changelog/v1.19.0-beta3/7505-gw-api-cipher-suites.yaml
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gateway2/translator/sslutils/ssl_utils_test.go
  projects/gateway2/wellknown/controller.go
  test/kubernetes/e2e/features/server_tls/edge_suite.go
  test/kubernetes/e2e/features/server_tls/k8s_suite.go
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-1.yaml
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-2.yaml
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-with-oneway.yaml
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-without-oneway.yaml
  test/kubernetes/e2e/features/server_tls/testdata/k8s/gateway.yaml
  test/kubernetes/e2e/features/server_tls/testdata/k8s/httproute.yaml
  test/kubernetes/e2e/features/server_tls/testdata/k8s/setup.yaml
  test/kubernetes/e2e/features/server_tls/types.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
  test/kubernetes/e2e/tests/validation_always_accept_tests.go
Labels: keep pr updated

#10564 [1.18] Backport SSL options
  changelog/v1.18.4/7505-gw-api-cipher-suites.yaml
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gateway2/translator/sslutils/ssl_utils_test.go
  projects/gateway2/wellknown/controller.go
  test/kubernetes/e2e/features/server_tls/edge_suite.go
  test/kubernetes/e2e/features/server_tls/k8s_suite.go
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-1.yaml
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-2.yaml
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-with-oneway.yaml
  test/kubernetes/e2e/features/server_tls/testdata/edge/vs-without-oneway.yaml
  test/kubernetes/e2e/features/server_tls/testdata/k8s/gateway.yaml
  test/kubernetes/e2e/features/server_tls/testdata/k8s/httproute.yaml
  test/kubernetes/e2e/features/server_tls/testdata/k8s/setup.yaml
  test/kubernetes/e2e/features/server_tls/types.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
  test/kubernetes/e2e/tests/validation_always_accept_tests.go
Labels: keep pr updated

#10563 [1.18] Backport configure NodePort with GatewayParams
  changelog/v1.18.4/7504-gwapi-static-node-ports.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway2/api/v1alpha1/gateway_parameters.md
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/templates/43-gatewayparameters.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
Labels: keep pr updated

#10561 gateway2: allow route delegation using well known label
  changelog/v1.19.0-beta3/deleg-label.yaml
  projects/gateway2/controller/controller.go
  projects/gateway2/query/httproute.go
  projects/gateway2/query/indexers.go
  projects/gateway2/translator/backendref/types.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation_helpers.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/testutils/inputs/delegation/label_based.yaml
  projects/gateway2/translator/testutils/outputs/delegation/label_based.yaml
  projects/gateway2/wellknown/delegation.go
  test/kubernetes/e2e/features/route_delegation/testdata/basic.yaml
Labels: keep pr updated, needs-port-k8s

#10566 [1.18] 6748-spawn-upstream-span-backport
  changelog/v1.18.4/6748-spawn-upstream-span-backport.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options/tracing/tracing.proto
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.clone.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.equal.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.hash.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.uniquehash.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
Labels: keep pr updated

#10567 [backport] gateway2: allow route delegation using well known label (#10561)
  changelog/v1.18.4/deleg-label.yaml
  projects/gateway2/controller/controller.go
  projects/gateway2/query/httproute.go
  projects/gateway2/query/indexers.go
  projects/gateway2/translator/backendref/types.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation_helpers.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/testutils/inputs/delegation/label_based.yaml
  projects/gateway2/translator/testutils/outputs/delegation/label_based.yaml
  projects/gateway2/wellknown/delegation.go
  test/kubernetes/e2e/features/route_delegation/testdata/basic.yaml
Labels: keep pr updated

#10554 feat: Add Match Conditions to the validation webhook
  changelog/v1.19.0-beta3/match-conditions.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  pkg/utils/kubeutils/kubectl/cli.go
  test/kubernetes/e2e/features/validation/split_webhook/suite.go
  test/kubernetes/e2e/features/validation/testdata/split-webhook/gloo-webhook-failure-policy-match-conditions.yaml
  test/kubernetes/e2e/features/validation/testdata/split-webhook/kube-webhook-failure-policy-match-conditions.yaml
  test/kubernetes/e2e/features/validation/types.go
Labels: keep pr updated

#10568 Should skip install update
  changelog/v1.19.0-beta3/ShouldSkipInstall-update.yaml
  test/kubernetes/e2e/test.go
Labels: keep pr updated

#10569 [1.18] feat: Add Match Conditions to the validation webhook
  changelog/v1.18.6/match-conditions.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  pkg/utils/kubeutils/kubectl/cli.go
  test/kubernetes/e2e/features/validation/split_webhook/suite.go
  test/kubernetes/e2e/features/validation/testdata/split-webhook/gloo-webhook-failure-policy-match-conditions.yaml
  test/kubernetes/e2e/features/validation/testdata/split-webhook/kube-webhook-failure-policy-match-conditions.yaml
  test/kubernetes/e2e/features/validation/types.go
Labels: keep pr updated

#10565 Doc fixes
  changelog/v1.19.0-beta3/doc-fixes.yaml
  docs/content/installation/advanced_configuration/gzip.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto.sk.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth-internal.proto
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth-internal.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#10573 Dump logs for all containers when test fails
  changelog/v1.19.0-beta3/dump-all-containers-logs-on-test-fail.yaml
  pkg/utils/statedumputils/state_dump.go
Labels: keep pr updated

#10574 only add istio automtls when label has value
  changelog/v1.19.0-beta4/istio-automtls-disabled.yaml
  projects/gateway2/krtcollections/endpoints.go
  projects/gloo/pkg/plugins/istio_automtls/helper.go
Labels: needs-port-k8s

#10579 Allows per test directory for generated files on failure
  changelog/v1.19.0-beta4/allow-per-test-directory-for-generated-files.yaml
  test/kubernetes/e2e/example/info_logging_test.go
  test/kubernetes/e2e/features/example/suite.go
  test/kubernetes/e2e/test.go
Labels: keep pr updated

#10583 fix glooctl install: Replace deprecated distutils
  changelog/v1.19.0-beta5/glooctl-install.yaml
  projects/gloo/cli/install.sh
  projects/gloo/cli/test.sh
Labels: keep pr updated

#10582 Add support for TLS for xDS with Gloo Gateway
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.19.0-beta5/k8s-gw-mtls-deployer.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/44-rbac.yaml
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/setup/ggv2setup.go
  projects/gateway2/wellknown/controller.go
  test/kubernetes/e2e/features/gloomtls/gloomtls_edge_suite.go
  test/kubernetes/e2e/features/gloomtls/gloomtls_k8s_gateway_suite.go
  test/kubernetes/e2e/features/gloomtls/testdata/certgen.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/hello-route.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/route-with-service.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/service-for-route.yaml
  test/kubernetes/e2e/features/gloomtls/types.go
  test/kubernetes/e2e/tests/gloomtls_k8s_gw_test.go
  test/kubernetes/e2e/tests/gloomtls_k8s_gw_tests.go
  test/kubernetes/e2e/tests/manifests/gloomtls-edge-gateway-test-helm.yaml
  tilt-settings.yaml
Labels: keep pr updated, needs-port-k8s

#10587 [backport] gateway2: skip non-Gloo Gateways
  changelog/v1.18.7/check-gw.yaml
  projects/gateway2/controller/start.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
Labels: keep pr updated

#10589 1.18.x mtls for xds in gg2
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.7/k8s-gw-mtls-deployer.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/44-rbac.yaml
  pkg/utils/kubeutils/kubectl/cli.go
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/setup/ggv2setup.go
  projects/gateway2/wellknown/controller.go
  test/kubernetes/e2e/features/gloomtls/gloomtls_edge_suite.go
  test/kubernetes/e2e/features/gloomtls/gloomtls_k8s_gateway_suite.go
  test/kubernetes/e2e/features/gloomtls/testdata/certgen.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/hello-route.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/route-with-service.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/service-for-route.yaml
  test/kubernetes/e2e/features/gloomtls/types.go
  test/kubernetes/e2e/tests/gloomtls_k8s_gw_test.go
  test/kubernetes/e2e/tests/gloomtls_k8s_gw_tests.go
  test/kubernetes/e2e/tests/manifests/gloomtls-edge-gateway-test-helm.yaml
  tilt-settings.yaml
Labels: keep pr updated

#10586 gateway2: skip non-Gloo Gateways
  changelog/v1.19.0-beta6/check-gw.yaml
  projects/gateway2/controller/start.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
Labels: keep pr updated, needs-port-k8s

#10592 upgrade solo-kit
  changelog/v1.19.0-beta6/solo-kit-bump.yaml
  go.mod
  go.sum
Labels: keep pr updated

#10593 [1.18] upgrade solo-kit
  changelog/v1.18.7/upgrade-solo-kit.yaml
  go.mod
  go.sum
Labels: keep pr updated
